version: "3"
services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: web
    command: "./bin/rails server -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_DB=vetor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  app-storage:
